In [1]:
import pandas as pd
from tqdm.auto import tqdm

from pathlib import Path

# always look for the latest csv file
csv_files = sorted(list(Path("../../data/processed").glob("*.csv")))

In [2]:

df = pd.read_csv(csv_files[-1])

In [5]:
# get number of null values for each column
df.isnull().sum()

StudentID               0
Attempted               0
Full                    0
Age                     0
Dev                     0
Internet                0
PercentageOfRepeats     0
PercentageOfHistDrop    0
TermCode                0
MajorChangedFromLast    0
NumberOfMajors          0
NumberOfUniqueMajors    0
CumGPALast              0
PercentageOfAbsence     0
Ethnicity               0
Gender                  0
IsHispanic              0
Target                  0
dtype: int64

In [3]:
df.head()

,StudentID,Attempted,Full,Age,Dev,Internet,PercentageOfRepeats,PercentageOfHistDrop,TermCode,MajorChangedFromLast,NumberOfMajors,NumberOfUniqueMajors,CumGPALast,PercentageOfAbsence,Ethnicity,Gender,IsHispanic,Target
0,101001184,16.0,1,27.0,0,0,0.250000,0.000000,B17C,0,3,1,2.6000,0.020000,"White, Non-Hispanic",Female,No,0
1,101001184,10.0,0,28.0,1,0,0.000000,0.000000,B18Q,1,5,2,2.4286,0.230769,"White, Non-Hispanic",Female,No,0
2,102001082,17.0,1,20.0,0,2,0.285714,0.047619,B17C,0,4,1,3.8478,0.090909,"White, Non-Hispanic",Female,No,1
3,102002426,14.0,1,23.0,0,2,0.000000,0.111111,B17C,1,9,2,2.9057,0.236842,Hispanic,Female,Yes,0
4,102002426,15.0,1,25.0,0,5,0.000000,0.095238,B19Q,0,13,3,2.8833,0.000000,Hispanic,Female,Yes,0

In [4]:
import pandas_profiling

profile = df.profile_report(title="Pandas Profiling Report")
profile.to_file("eda.html")

c:\Users\Owner\Anaconda3\envs\ml\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Owner\AppData\Local\Temp\ipykernel_15336\746266517.py:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  import pandas_profiling
Summarize dataset:  76%|███████▌  | 19/25 [00:02<00:01,  3.55it/s, Calculate auto correlation]            c:\Users\Owner\Anaconda3\envs\ml\lib\site-packages\multimethod\__init__.py:315: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  return func(*args, **kwargs)
Summarize dataset: 100%|██████████| 127/127 [00:36<00:00,  3.53it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:10<00:00, 10.71s/it]
Render HTML: 100%|██████████| 1/1 [00:12<00:00, 12.27s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00,  1.78it/s]